### ISSUE TITLE
Drivers stop working after reboot.

### ISSUE THREAD

**Issue by TheAlikA** [chris1111/VoodooHDA-2.9.2-Clover-V15#10]
These drivers work great in OSX 10.15.3 after install, but after reboot they stop working, and nothing I do can bring back the audio, I tried deleting all the files, rebooting and re-installing... but that doesnt even work. all my files can be found [**here**](https://www.tonymacx86.com/threads/success-10-15-3-asus-rog-strix-z270g-catalina-efi-files.292395/) 
![VooDooDHA2.9.2.15](https://i.imgur.com/O0OlGfG.png)

![VooDooDHA2.9.2.15](https://i.imgur.com/as5r8ZP.png)

**Comment by chris1111** [comment]
Make sure Inject kext to yes
[Inject kext Yes](https://i25.servimg.com/u/f25/18/50/18/69/captu819.png)

Program work I have test release V15 to 10.6 at 10.15.4 so issue is on your side 100%

**Comment by TheAlikA** [comment]
Thanks, but not very helpful, as I mentioned, it works for the first time until restart, thereafter it does not. was hoping for some kind of input rather than "it works, you are wrong" type of reply.

**Comment by TheAlikA** [comment]
Thanks so much
in addition to your fix I added FixDHA  and all worked!
You are awesome!
[error](https://i.imgur.com/lPPU9md.png)

**Comment by shamesung** [comment]
Having the same issue none of the above steps resolved this. Works great after install and then the next reboot it stops
