### ISSUE TITLE
Microphone Click interference

### ISSUE THREAD

**Issue by TheAlikA** [chris1111/VoodooHDA-2.9.2-Clover-V15#11]
![Mic interference](https://i.imgur.com/W9mIIYr.png)
Firstly thank you for such a great kext!

I am getting a microphone clicking sound interference when recording from the back [listen here](https://voca.ro/cgUGCUxcFlh) and just white noise with no recording from the front. any clue as to what it may be?
p.s. blue Line-in is not detected.

**Comment by chris1111** [comment]
Right clic then chow package Contents on VoodooHDA.kext/Contents/Info.plist
open with textedit.app
try to setup this portion like that's

<key>MixerValues</key>
    <dict>
	<key>PCM</key>
	<integer>90</integer>
	<key>Rec</key>
	<integer>90</integer>
	<key>iGain</key>
	<integer>0</integer>
	<key>iMix</key>
	<integer>30</integer>
    </dict>

You can test other value but reboot after change the plist to make effect
