### ISSUE TITLE
Catalina on prebook 4530s everything fine , except it does not recognises headphone jack 

### ISSUE THREAD

**Issue by kenimalo** [chris1111/VoodooHDA-2.9.2-Clover-V15#14]
hello, thanks for you work , and well done . 
can you help me with this issue , sound works fine , graphics intel 3000 works good with legacy patched video, but sound won't go to headphones when I put in the jack, remains speakers. 
can you help me with that please?
(some days ago I had Yosemite and this problem was not with that)

**Comment by chris1111** [comment]
Dis you remove AppleALC.kext in Clover ?

**Comment by kenimalo** [comment]
sorry because I am not very good at this.. 
I made a search... I have AppleALC.kext in MacOS drive but not in efi/clover

**Comment by chris1111** [comment]
If you have in macOS Drive your net using my program [HP ProBook EliteBook macOS ](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator)
