### ISSUE TITLE
DELL XPS 9560 & ULTRASHARP U3415W - No Audio Output from HDMI

### ISSUE THREAD

**Issue by saitek1710** [chris1111/VoodooHDA-2.9.2-Clover-V15#18]
Hi Chris,

Im having a problem with the HDMI audio output for my monitor 

It is showing the audio output source of HDMI but "the selected device has no output controls" 

Would you give some advice what i should do? Thanks

<img width="1411" alt="Screen Shot 2020-06-20 at 22 46 55" src="https://user-images.githubusercontent.com/67156601/85202184-f3a5ca00-b347-11ea-8df9-f89998ddcf1e.png">

**Comment by chris1111** [comment]
After High Sierra HDMI seems to no longer work on IGPU and VoodooHDA
