### ISSUE TITLE
No HDMI sound after sleep

### ISSUE THREAD

**Issue by evgenyrud** [chris1111/VoodooHDA-2.9.2-Clover-V15#20]
I have Intel NUC10i7FNK. It has Realtek ALC256
After sleep no sound anymore on Digital Audio (HDMI).
OS: Catalina 10.15.5
HDMI sound from speakers connected to LG 4K monitor.
Ioreg logs provided forum

**Comment by chris1111** [comment]
Your just lucky to have Audio HDMI lots people don't have HDMI with VoodooHDA 
for your problem I have no idea because it can come from many things.

**Comment by evgenyrud** [comment]
Hi,

Good to know that I'm luck and at list somehow my HDMI works.
I read a lot and know that there were such issues in the past and solution
was provided by CodecCommander.kext. Tried that but it didn't work.

Maybe after resume I need to reinitialize somehow VoodooHDA or create a
script which will run on resume to reinitialize VoodooHDA?

What do you think can be done?

Thanks,
Evgeny

**Comment by chris1111** [comment]
I don't know?
