### ISSUE TITLE
Possible to add new Codec?

### ISSUE THREAD

**Issue by thefiredragon** [chris1111/VoodooHDA-2.9.2-Clover-V15#22]
Dear all, it's possible to add a new codec? 
I've little throubble with applealc on new codec.
My Notebook uses an ALC287 codec, this codec was added to applealc but it's not working, native layout for my machine was 7 and mine uses as default layout 3.
I tried a lot so I would ask if it could possible to get it with voodoohda working, best regards, Dan

**Comment by chris1111** [comment]
Did you try voodooHDA without AppleALC ?

**Comment by thefiredragon** [comment]
Yes I did, but was not working, too

**Comment by chris1111** [comment]
You need to ask to Developper Slice.
